server:
    port: 9000

spring:
    application:
        name: halak game
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
        username: sa
        password:

    liquibase:
        change-log: classpath:liquibase/changesets/master-changelog.xml
        contexts: "init, data"
        enabled: true
        #labels: "dev OR all"

    h2.console.enabled: true
    h2.console.path: /h2-console

    jackson.serialization:
        INDENT_OUTPUT: true

    #jpa.hibernate.ddl-auto: validate

    jpa.hibernate.ddl-auto: validate

logging:
    level:
      root: DEBUG
      org.springframework.web: DEBUG
